name: main CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  frontworkflow:
    uses: ./jwt_front/.github/workflows/FrontCI.yml@v1
  backworkflow:
    uses: ./jwt_learn/.github/workflows/javamvenci.yml@v1
